#!/bin/bash
# title			:BASHRC System
# description	:The help system for BASHRC System
# author		:Jessica Brown
# date			:2019-12-20
# version		:4
# usage			:After install, just open a terminal
# notes			:This script is self installing
# bash_version	:4.1.5(1)-release
# ==============================================================================
# TODO:
#   Need to make this dynamically generated as new modules are added to the module folder
#   Vision: Have a function called <modulename>_help() it will contain a 1 liner and a
#           full description. The one liner would be generated inside this file and the
#           full description would be if they call that command with --help or (-h)

function commands() {
    cat ${binLocation}${dirSeperator}${helpSubPath}${dirSeperator}hlp_main.dat
}
