#!/bin/bash -i
# title			:Add Alias Module for BASH System
# description	:To create and alias from the previous command and 
#                add it the the aliases.sh file for permanency
# author		:Jessica Brown
# date			:2020-01-25
# version		:2.0.0
# usage			:After install, just open a terminal
# notes			:This script is self installing
# bash_version	:4.1.5(1)-release
# ==============================================================================

function addalias() {
    if [ "$1" = "--help" ] || [ "$1" = "-h" ]; then
        cat ${binLocation}${dirSeperator}${helpSubPath}${dirSeperator}hlp_addalias.dat
    else
        if [[ "$#" -ne 1 ]]; then
            echo -e "${Red}USAGE: ${Silver}addalias <alias>${txtReset}"
            echo -e "       ${Silver}addalias -h [--help]${txtReset}"
            return 0
        elif [[ -n "$(alias $1 2>/dev/null)" ]]; then
            echo "${Red}Alias already exists!${txtReset}"
            return 0
        fi

        lastcmd=$(history | tail -2 | head -1 | cut -c8-999)
        if [[ "${lastcmd}" != "" ]]; then
            echo -e "alias $1=\"${lastcmd}\"\n" >> ${orLocation}/or_bash_aliases.sh
            reload
            echo "${Lime}Alias was added successfully.${txtReset}"
        else
            echo "${Red}NOTICE: ${White}History does not show any previous commands to be entered, use --help for more information.${txtReset}"
        fi
    fi
}