#!/usr/bin/env bash

function duplicate() {
    # title             :Enhanced BASH Backup File System
    # description       :A module to backup a directory or file
    # author            :Jessica Brown
    # date              :2020-01-25
    # usage			    :bakup [--help|-h] [directory/|filename.ext]
    # notes			    :
    # bash_version	    :4.4.19(1)-release
    # ==============================================================================
    local version="2.0.0"
    baktimestamp=$(LC_ALL=C date +%Y%m%d_%H%M%S)

    if [ "$1" = "--help" ] || [ "$1" = "-h" ]; then
        cat ${binLocation}${dirSeperator}${helpSubPath}${dirSeperator}hlp_bakup.dat
    else
        if [ -d $archiveLocation ]; then
            if [ -d $1 ]; then
                bakFolder=$(basename "$1")-${baktimestamp}
                mkdir -p ${archiveLocation}/${bakFolder}
                rsync -aqr $1 ${archiveLocation}/${bakFolder}
                echo -e "The folder ${Aqua}${1} has been backed up at ${HOME}/.backup/${bakFolder}"
                diff -qr ${1}/ ${archiveLocation}/${bakFolder}/
            elif [ -f $1 ]; then
                cp $1 ${archiveLocation}/`basename $1`-${baktimestamp}.backup
            else
                warning "${1} file or directory not found."
            fi
        else
            echo -e "${Red}ERROR: ${Silver}The ${archiveLocation} folder does not exist in the home folder, ${CornflowerBlue}$1${Silver} was not backed up. Create the ${archiveLocation} and try again.${txtReset}"
        fi
    fi
}
